"""The notes board (SPEC §4.5).

Markdown bodies, pinning, tags, per-item visibility, and full-text search.

**Search is the dangerous part.** Yuvomi's spec notes its FTS index is "scoped by
user visibility"; a search that queries the index directly is the easiest way to
hand someone a private note they cannot otherwise reach. Here the search vector
is a column on the notes table itself rather than a separate index table, so a
search *is* a select on `notes` — which means the scoping guard applies to it
exactly as it does to any other read, and cannot be bypassed by accident.
"""

from __future__ import annotations

import datetime as dt
from uuid import UUID

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from home_ops.db import Base
from home_ops.scoping import OwnedVisibleMixin

#: Postgres text-search configuration. 'english' gives stemming, so "shopping"
#: matches "shop". Worth revisiting if the household is not English-speaking.
SEARCH_CONFIG = "english"

MAX_TAG_LENGTH = 32


class NoteTag(Base):
    """One tag on one note.

    A plain string per row rather than a tags table with a join: a household has
    tens of tags, not thousands, and this keeps "rename a tag" a single UPDATE
    without a second entity to keep tidy.
    """

    __tablename__ = "note_tags"

    note_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("notes.id", ondelete="CASCADE"), primary_key=True
    )
    tag: Mapped[str] = mapped_column(String(MAX_TAG_LENGTH), primary_key=True)

    __table_args__ = (
        CheckConstraint("tag = lower(tag)", name="tag_is_lowercase"),
        CheckConstraint("length(trim(tag)) > 0", name="tag_not_blank"),
        Index("ix_note_tags_tag", "tag"),
    )


class Note(OwnedVisibleMixin, Base):
    """A markdown note. Carries owner_id, visibility and created_at from the mixin."""

    __tablename__ = "notes"

    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    #: Markdown source. Rendered — and sanitised — in the browser; nothing here
    #: is ever trusted as HTML.
    body: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))

    #: A palette key, not a hex. Same rule as member hues and task categories.
    color_key: Mapped[str | None] = mapped_column(String(32), nullable=True)
    is_pinned: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))

    #: Manual board order, lowest first.
    #:
    #: Shared across the household rather than per-member — the same choice
    #: already made for `is_pinned`. This is one noticeboard, and a note somebody
    #: moved to the front should be at the front for everybody. A personal
    #: ordering would need a per-user table, and having both would leave two
    #: answers to "why is this note here".
    position: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))

    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    #: Generated by Postgres, so it can never drift from the note. Title is
    #: weighted above body: a word in the title is a stronger signal than the
    #: same word buried in a paragraph.
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            f"setweight(to_tsvector('{SEARCH_CONFIG}', coalesce(title, '')), 'A') || "
            f"setweight(to_tsvector('{SEARCH_CONFIG}', coalesce(body, '')), 'B')",
            persisted=True,
        ),
        nullable=False,
    )

    tags: Mapped[list[NoteTag]] = relationship(
        cascade="all, delete-orphan", passive_deletes=True, lazy="selectin"
    )

    __table_args__ = (
        CheckConstraint("length(trim(title)) > 0", name="title_not_blank"),
        Index("ix_notes_search_vector", "search_vector", postgresql_using="gin"),
        Index("ix_notes_owner_id", "owner_id"),
        # The board's default ordering: pinned first, then manual position,
        # then most recently touched.
        Index("ix_notes_board_order", "is_pinned", "position", "updated_at"),
    )
