"""shopping list

Revision ID: 753a84c16137
Revises: 9672592a257e
Created: 2026-07-31 17:58:37.822761+00:00

Phase 5d of SPEC §4.6: the shopping list.

One shared table, like the meal plan, and for the same reason: there is one
household and one trip to the shop, so a list two people cannot both read is not
a shopping list. No `visibility` column — see `shopping_models.py`. What a
*generated* line may contain is controlled where it is generated, in
`shopping_service.generate`, which reads recipes through the scoped query so a
recipe the caller may not open cannot leak onto the list an ingredient at a time.

`ingredient_id` is ON DELETE **RESTRICT**, unlike every other reference to
`ingredients` in this schema. Tidying the ingredient vocabulary must not quietly
remove something from a list somebody is holding in a shop; the delete should
fail and say so.

`is_uncombined` exists because §4.6 asks the aggregation to combine quantities
"or flag that it can't". 200 g and 2 cups of the same flour cannot be added
without a density a recipe does not carry, so they stay two lines and this
column is what lets the UI say why.

`checked_by_id` is ON DELETE SET NULL: removing a member must not take the milk
off the list, only the note about who fetched it.

Reversible: `downgrade()` drops the table. Nothing references it.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "753a84c16137"
down_revision: str | None = "9672592a257e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("is_generated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_uncombined", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_checked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ingredient_id IS NOT NULL OR (title IS NOT NULL AND length(trim(title)) > 0)",
            name=op.f("ck_shopping_items_item_names_something"),
        ),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity > 0", name=op.f("ck_shopping_items_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["checked_by_id"],
            ["users.id"],
            name=op.f("fk_shopping_items_checked_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_shopping_items_ingredient_id_ingredients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_shopping_items_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_items")),
    )
    op.create_index(
        "ix_shopping_items_ingredient_id", "shopping_items", ["ingredient_id"], unique=False
    )
    op.create_index("ix_shopping_items_position", "shopping_items", ["position"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shopping_items_position", table_name="shopping_items")
    op.drop_index("ix_shopping_items_ingredient_id", table_name="shopping_items")
    op.drop_table("shopping_items")
    # ### end Alembic commands ###
