"""shopping lists

Revision ID: a2de2cd6fed1
Revises: 753a84c16137
Created: 2026-07-31 19:23:53.167000+00:00

Phase 6 of SPEC §4.12: shopping leaves the Kitchen and becomes many lists.

**`shopping_lists` is visibility-bearing**, unlike the single list it replaces.
It carries the mixin's `owner_id` / `visibility` / `created_at`, so §4.2's three
states — private, shared with named members (via `shopping_list_shares`),
household — come from the engine that already has no admin bypass. The single
shared list of Phase 5d was right for one list and stops being right the moment
a gift list is possible.

**At most one list may be the meal-plan target**, and the database says so: a
partial unique index on a constant expression, `WHERE is_meal_plan_target`. A
rule the schema states cannot be got wrong by a second code path later.

**`shopping_items.list_id` is added in three steps, not one.** Nullable, then
backfilled, then NOT NULL — because adding a NOT NULL column to a table with
rows in it fails, and this table has rows in it on the machine this is being
written on. The backfill creates one list named "Groceries", household-visible
and flagged as the meal-plan target, owned by the oldest admin, and puts every
existing line on it. Nothing is lost and nothing needs doing by hand.

**`section` is for lines that are not ingredients.** An ingredient takes its
section from `ingredients.aisle`, which stays in the Kitchen where the
ingredient lives; a text line has nothing shared to hang it on, so it carries
its own.

Reversible, with one honest caveat stated rather than hidden: `downgrade()`
drops `list_id` and both tables, so every line collapses back into one
undifferentiated list and **which list a line was on is lost**. The lines
themselves are not. Going down and back up leaves one list called "Groceries"
holding everything, which is exactly the Phase 5d state this replaced.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a2de2cd6fed1"
down_revision: str | None = "753a84c16137"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Every module the permission vocabulary knows, as `policy.Module` has it.
#: `test_permissions_api.py` reads this constraint back out of the database and
#: compares it with the enum, so the two cannot drift again.
KNOWN_MODULES = (
    "users",
    "settings",
    "audit",
    "tasks",
    "notes",
    "calendar",
    "kitchen",
    "shopping",
)


def _set_known_modules(modules: tuple[str, ...]) -> None:
    op.drop_constraint("module_is_known", "access_permissions", type_="check")
    values = ", ".join(f"'{module}'" for module in modules)
    op.create_check_constraint(
        "module_is_known", "access_permissions", f"module IN ({values})"
    )


def upgrade() -> None:
    # `shopping` is a module now, so a deviation may name it. This also repairs
    # an omission: the Phase 5a migration wrote the `downgrade()` half that
    # narrows this constraint back but never the `upgrade()` half that widens
    # it, so `kitchen` has been missing from it since 5a and any attempt to set
    # a per-member Kitchen permission failed with an IntegrityError. Nothing
    # exercised that path, so a green suite shipped it.
    _set_known_modules(KNOWN_MODULES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_lists",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "is_meal_plan_target", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_shopping_lists_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_shopping_lists_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_lists")),
    )
    op.create_index("ix_shopping_lists_position", "shopping_lists", ["position"], unique=False)
    op.create_index(
        "uq_shopping_lists_meal_plan_target",
        "shopping_lists",
        [sa.literal_column("(is_meal_plan_target)")],
        unique=True,
        postgresql_where=sa.text("is_meal_plan_target"),
    )
    op.create_table(
        "shopping_list_shares",
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "shared_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["shopping_lists.id"],
            name=op.f("fk_shopping_list_shares_list_id_shopping_lists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_shopping_list_shares_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("list_id", "user_id", name=op.f("pk_shopping_list_shares")),
    )
    op.create_index(
        "ix_shopping_list_shares_user_id", "shopping_list_shares", ["user_id"], unique=False
    )
    op.add_column("shopping_items", sa.Column("section", sa.String(length=64), nullable=True))

    # Nullable first. The column is NOT NULL by the end of this function, but it
    # cannot start that way on a table that already has rows.
    op.add_column("shopping_items", sa.Column("list_id", sa.UUID(), nullable=True))

    connection = op.get_bind()
    orphans = connection.execute(
        sa.text("SELECT count(*) FROM shopping_items WHERE list_id IS NULL")
    ).scalar_one()

    if orphans:
        # Everything that existed before there were lists goes onto one, so the
        # upgrade needs no tidying up afterwards. Owned by the oldest admin
        # because a list must have an owner and that is the account that
        # certainly exists; visibility is `household`, matching the shared list
        # these rows were on a moment ago.
        default_list_id = connection.execute(
            sa.text(
                """
                INSERT INTO shopping_lists
                    (name, is_meal_plan_target, position, owner_id, visibility)
                SELECT 'Groceries', true, 0, id, 'household'
                FROM users
                WHERE role = 'admin'
                ORDER BY created_at
                LIMIT 1
                RETURNING id
                """
            )
        ).scalar_one()
        connection.execute(
            sa.text("UPDATE shopping_items SET list_id = :list_id WHERE list_id IS NULL"),
            {"list_id": default_list_id},
        )

    op.alter_column("shopping_items", "list_id", nullable=False)
    op.create_index("ix_shopping_items_list_id", "shopping_items", ["list_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_shopping_items_list_id_shopping_lists"),
        "shopping_items",
        "shopping_lists",
        ["list_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Deviations naming a module that is about to stop existing would violate
    # the narrower CHECK, so they go first. Note this restores the *correct*
    # earlier state rather than the one that was actually there: `kitchen`
    # stays, because leaving it out was the bug.
    op.execute("DELETE FROM access_permissions WHERE module = 'shopping'")
    _set_known_modules(tuple(m for m in KNOWN_MODULES if m != "shopping"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_shopping_items_list_id_shopping_lists"), "shopping_items", type_="foreignkey"
    )
    op.drop_index("ix_shopping_items_list_id", table_name="shopping_items")
    op.drop_column("shopping_items", "section")
    op.drop_column("shopping_items", "list_id")
    op.drop_index("ix_shopping_list_shares_user_id", table_name="shopping_list_shares")
    op.drop_table("shopping_list_shares")
    op.drop_index(
        "uq_shopping_lists_meal_plan_target",
        table_name="shopping_lists",
        postgresql_where=sa.text("is_meal_plan_target"),
    )
    op.drop_index("ix_shopping_lists_position", table_name="shopping_lists")
    op.drop_table("shopping_lists")
    # ### end Alembic commands ###
