"""api tokens

Revision ID: 5e6d3dc8b485
Revises: 6c0c3bf7cc3f
Created: 2026-08-02 01:30:08.483202+00:00

Every migration must be reversible (SPEC §0). `downgrade()` is not optional and
is not `pass` — if a change genuinely cannot be reversed, say why here and raise
in `downgrade()` so it fails loudly rather than silently doing nothing.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5e6d3dc8b485"
down_revision: str | None = "6c0c3bf7cc3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_api_tokens_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index("ix_api_tokens_token_hash", "api_tokens", ["token_hash"], unique=False)
    op.create_index("ix_api_tokens_user_id", "api_tokens", ["user_id"], unique=False)
    op.create_table(
        "api_token_scopes",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("access", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "access IN ('none', 'read', 'write')", name=op.f("ck_api_token_scopes_access_is_known")
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["api_tokens.id"],
            name=op.f("fk_api_token_scopes_token_id_api_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_id", "module", name=op.f("pk_api_token_scopes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_token_scopes")
    op.drop_index("ix_api_tokens_user_id", table_name="api_tokens")
    op.drop_index("ix_api_tokens_token_hash", table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
