"""contacts

Revision ID: 568497e41c55
Revises: a2de2cd6fed1
Created: 2026-08-01 07:32:52.375718+00:00

Phase 7 of SPEC §4.7: the contact directory.

**One visibility-bearing parent and four children.** Only `contacts` carries
`owner_id` / `visibility`; phones, emails, addresses and tags inherit it and are
reached only through a scoped contact. They are therefore *not* registered with
the scoping guard, and `service.py` says so where it matters.

**`search_vector` is a generated column on `contacts`**, not a separate index
table. That makes a search an ordinary SELECT on a visibility-bearing table, so
the guard covers it and it cannot be bypassed by accident — the same argument
`notes` makes, and it matters more here, because a directory is exactly what
somebody would search for a name they should not be able to find.

**`contacts` joins the module CHECK on `access_permissions`.** Both halves are
written this time. The Phase 5a migration wrote only the `downgrade()` half for
`kitchen` and left the constraint refusing a module the code had, which nothing
noticed for two phases; `test_permissions_api.py` now reads the constraint back
and compares it with `policy.Module`, so this cannot repeat quietly.

Reversible: `downgrade()` drops the four tables and narrows the CHECK, deleting
any `contacts` deviation first so the narrower constraint can be applied.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "568497e41c55"
down_revision: str | None = "a2de2cd6fed1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Every module the permission vocabulary knows, as `policy.Module` has it.
KNOWN_MODULES = (
    "users",
    "settings",
    "audit",
    "tasks",
    "notes",
    "calendar",
    "kitchen",
    "shopping",
    "contacts",
)


def _set_known_modules(modules: tuple[str, ...]) -> None:
    op.drop_constraint("module_is_known", "access_permissions", type_="check")
    values = ", ".join(f"'{module}'" for module in modules)
    op.create_check_constraint("module_is_known", "access_permissions", f"module IN ({values})")


def upgrade() -> None:
    _set_known_modules(KNOWN_MODULES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("given_name", sa.String(length=100), nullable=True),
        sa.Column("family_name", sa.String(length=100), nullable=True),
        sa.Column("organisation", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(display_name, '')), 'A') || setweight(to_tsvector('english', coalesce(organisation, '')), 'B') || setweight(to_tsvector('english', coalesce(job_title, '')), 'C') || setweight(to_tsvector('english', coalesce(notes, '')), 'D')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(display_name)) > 0", name=op.f("ck_contacts_display_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_contacts_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(
        "ix_contacts_display_name",
        "contacts",
        [sa.literal_column("lower(display_name)")],
        unique=False,
    )
    op.create_index("ix_contacts_owner_id", "contacts", ["owner_id"], unique=False)
    op.create_index(
        "ix_contacts_search_vector",
        "contacts",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "contact_addresses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("locality", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("postcode", sa.String(length=32), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_addresses_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_addresses")),
    )
    op.create_index(
        "ix_contact_addresses_contact_id", "contact_addresses", ["contact_id"], unique=False
    )
    op.create_table(
        "contact_emails",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=True),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "length(trim(address)) > 0", name=op.f("ck_contact_emails_address_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_emails_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_emails")),
    )
    op.create_index("ix_contact_emails_contact_id", "contact_emails", ["contact_id"], unique=False)
    op.create_table(
        "contact_phones",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=True),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "length(trim(number)) > 0", name=op.f("ck_contact_phones_number_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_phones_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_phones")),
    )
    op.create_index("ix_contact_phones_contact_id", "contact_phones", ["contact_id"], unique=False)
    op.create_table(
        "contact_tags",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.CheckConstraint("length(trim(tag)) > 0", name=op.f("ck_contact_tags_tag_not_blank")),
        sa.CheckConstraint("tag = lower(tag)", name=op.f("ck_contact_tags_tag_is_lowercase")),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_tags_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("contact_id", "tag", name=op.f("pk_contact_tags")),
    )
    op.create_index("ix_contact_tags_tag", "contact_tags", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Deviations naming a module that is about to stop existing would violate
    # the narrower CHECK, so they go first.
    op.execute("DELETE FROM access_permissions WHERE module = 'contacts'")
    _set_known_modules(tuple(m for m in KNOWN_MODULES if m != "contacts"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contact_tags_tag", table_name="contact_tags")
    op.drop_table("contact_tags")
    op.drop_index("ix_contact_phones_contact_id", table_name="contact_phones")
    op.drop_table("contact_phones")
    op.drop_index("ix_contact_emails_contact_id", table_name="contact_emails")
    op.drop_table("contact_emails")
    op.drop_index("ix_contact_addresses_contact_id", table_name="contact_addresses")
    op.drop_table("contact_addresses")
    op.drop_index("ix_contacts_search_vector", table_name="contacts", postgresql_using="gin")
    op.drop_index("ix_contacts_owner_id", table_name="contacts")
    op.drop_index("ix_contacts_display_name", table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
