"""shopping quantity override

Revision ID: 6c0c3bf7cc3f
Revises: cec033c82a5b
Created: 2026-08-01 21:20:57.590468+00:00

An amount typed over the one the meal plan worked out (SPEC §4.12).

"The recipes need two onions, buy four" — and the point is that it survives the
next build. A flag rather than turning the line manual: a manual line carrying
the same ingredient would be *added to* by the next build rather than replaced,
and the shopper would end up with two rows for onions. Flagged, `generate()`
carries the amount across a rebuild exactly as it already carries a tick across.

Only meaningful on a generated line. On a manual one the quantity is simply the
quantity and there is nothing to override, which is why the service refuses to
set the flag there rather than the column forbidding it — a CHECK would have to
name `is_generated`, and a row flipping from generated to manual is not a state
this table has.

Reversible: `downgrade()` drops the column, and any override reverts to being
recomputed on the next build.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c0c3bf7cc3f"
down_revision: str | None = "cec033c82a5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shopping_items",
        sa.Column(
            "quantity_overridden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shopping_items", "quantity_overridden")
    # ### end Alembic commands ###
