"""meal plan entries

Revision ID: 9672592a257e
Revises: 8014dbc3500f
Created: 2026-07-31 04:12:27.036606+00:00

Phase 5c of SPEC §4.6: the weekly planner.

One table, and no `visibility` column on it — deliberately. There is one
household and one dinner, so the plan is shared and everybody needs to know
Tuesday is taken. `owner_id` records who put it there for the audit trail; it
decides nothing about who may look. Every other ownable record in this schema
carries a visibility, so its absence here is a statement rather than an
oversight, and `plan_models.py` says so at length.

`recipe_id` is ON DELETE **CASCADE**, not SET NULL: deleting a recipe should take
it off the plan. SET NULL would leave an entry occupying a Tuesday with no way
left to say what it was.

The `entry_names_something` CHECK is what keeps a blank off the planner — an
entry must be a recipe or a piece of text, and §4.6's "a planned meal can be
saved back as a recipe" is only meaningful if the second is allowed.

Reversible: `downgrade()` drops the table. Nothing else references it, so
nothing else has to be unpicked first.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9672592a257e"
down_revision: str | None = "8014dbc3500f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_plan_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slot IN ('breakfast', 'lunch', 'dinner', 'side')",
            name=op.f("ck_meal_plan_entries_slot_is_known"),
        ),
        sa.CheckConstraint(
            "recipe_id IS NOT NULL OR (title IS NOT NULL AND length(trim(title)) > 0)",
            name=op.f("ck_meal_plan_entries_entry_names_something"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_meal_plan_entries_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_meal_plan_entries_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_plan_entries")),
    )
    op.create_index(
        "ix_meal_plan_entries_date",
        "meal_plan_entries",
        ["plan_date", "slot", "position"],
        unique=False,
    )
    op.create_index(
        "ix_meal_plan_entries_recipe_id", "meal_plan_entries", ["recipe_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meal_plan_entries_recipe_id", table_name="meal_plan_entries")
    op.drop_index("ix_meal_plan_entries_date", table_name="meal_plan_entries")
    op.drop_table("meal_plan_entries")
    # ### end Alembic commands ###
