"""health records

Revision ID: cec033c82a5b
Revises: 568497e41c55
Created: 2026-08-01 16:03:13.390760+00:00

Phase 8 of SPEC §4.8: health records — the most sensitive data in the system.

**Every health table pins `visibility` to 'assignees' with a CHECK.** That is
what makes "private to the subject by default" a property of the schema rather
than of whichever code path wrote the row. `household` is unreachable: a health
record visible to the whole household through a mistyped field is precisely the
failure this module exists to prevent. With an empty share list, 'assignees'
means the subject alone.

**`owner_id` is the subject, not the author.** `recorded_by_id` is the author.
A parent logging a child's weight writes a row the *child* owns, and visibility
is evaluated against the owner — so writing a record for somebody grants no
continuing sight of their history.

**`health_shares` is the only sharing control**, and it is per person rather
than per record: nobody shares a blood pressure reading one at a time. Revoking
is one DELETE and takes effect on the next read, because nothing is copied onto
the records.

**No column anywhere here stores a judgment.** Lab reference ranges are the
lab's own numbers transcribed off somebody's report; there is no "high", "low",
"abnormal" or risk score, and §4.8 forbids adding one.

`health` joins the module CHECK on `access_permissions`, both halves written.

Reversible: `downgrade()` drops the seven tables and narrows the CHECK. It
destroys health records, which is the point of a downgrade and worth saying out
loud before anybody runs one on a machine that matters.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cec033c82a5b"
down_revision: str | None = "568497e41c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


KNOWN_MODULES = (
    "users",
    "settings",
    "audit",
    "tasks",
    "notes",
    "calendar",
    "kitchen",
    "shopping",
    "contacts",
    "health",
)


def _set_known_modules(modules: tuple[str, ...]) -> None:
    op.drop_constraint("module_is_known", "access_permissions", type_="check")
    values = ", ".join(f"'{module}'" for module in modules)
    op.create_check_constraint("module_is_known", "access_permissions", f"module IN ({values})")


def upgrade() -> None:
    _set_known_modules(KNOWN_MODULES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("happened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("distance_miles", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility = 'assignees'", name=op.f("ck_activity_entries_never_household_visible")
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes > 0",
            name=op.f("ck_activity_entries_duration_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_activity_entries_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_activity_entries_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_entries")),
    )
    op.create_index(
        "ix_activity_entries_owner_time",
        "activity_entries",
        ["owner_id", "happened_at"],
        unique=False,
    )
    op.create_table(
        "health_shares",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("viewer_id", sa.UUID(), nullable=False),
        sa.Column("granted_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("subject_id <> viewer_id", name=op.f("ck_health_shares_no_self_share")),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["users.id"],
            name=op.f("fk_health_shares_granted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["users.id"],
            name=op.f("fk_health_shares_subject_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["viewer_id"],
            ["users.id"],
            name=op.f("fk_health_shares_viewer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subject_id", "viewer_id", name=op.f("pk_health_shares")),
    )
    op.create_index("ix_health_shares_viewer_id", "health_shares", ["viewer_id"], unique=False)
    op.create_table(
        "lab_reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("lab_name", sa.String(length=200), nullable=True),
        sa.Column("collected_on", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility = 'assignees'", name=op.f("ck_lab_reports_never_household_visible")
        ),
        sa.CheckConstraint("length(trim(title)) > 0", name=op.f("ck_lab_reports_title_not_blank")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_lab_reports_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_lab_reports_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_reports")),
    )
    op.create_index(
        "ix_lab_reports_owner_collected", "lab_reports", ["owner_id", "collected_on"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dose", sa.String(length=100), nullable=True),
        sa.Column("form", sa.String(length=32), nullable=True),
        sa.Column("schedule", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("stopped_on", sa.Date(), nullable=True),
        sa.Column("stock_count", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("refill_at", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility = 'assignees'", name=op.f("ck_medications_never_household_visible")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_medications_name_not_blank")),
        sa.CheckConstraint(
            "stock_count IS NULL OR stock_count >= 0",
            name=op.f("ck_medications_stock_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_medications_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_medications_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medications")),
    )
    op.create_index("ix_medications_owner_id", "medications", ["owner_id"], unique=False)
    op.create_table(
        "vital_readings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("value", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("secondary_value", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility = 'assignees'", name=op.f("ck_vital_readings_never_household_visible")
        ),
        sa.CheckConstraint("length(trim(unit)) > 0", name=op.f("ck_vital_readings_unit_not_blank")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_vital_readings_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_vital_readings_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vital_readings")),
    )
    op.create_index(
        "ix_vital_readings_owner_kind_time",
        "vital_readings",
        ["owner_id", "kind", "measured_at"],
        unique=False,
    )
    op.create_table(
        "lab_analytes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("text_value", sa.String(length=120), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("reference_low", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("reference_high", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("reference_text", sa.String(length=120), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_lab_analytes_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["lab_reports.id"],
            name=op.f("fk_lab_analytes_report_id_lab_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_analytes")),
    )
    op.create_index("ix_lab_analytes_report_id", "lab_analytes", ["report_id"], unique=False)
    op.create_table(
        "medication_doses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
            name=op.f("fk_medication_doses_medication_id_medications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_medication_doses_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_doses")),
    )
    op.create_index(
        "ix_medication_doses_medication_id",
        "medication_doses",
        ["medication_id", "taken_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM access_permissions WHERE module = 'health'")
    _set_known_modules(tuple(m for m in KNOWN_MODULES if m != "health"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_medication_doses_medication_id", table_name="medication_doses")
    op.drop_table("medication_doses")
    op.drop_index("ix_lab_analytes_report_id", table_name="lab_analytes")
    op.drop_table("lab_analytes")
    op.drop_index("ix_vital_readings_owner_kind_time", table_name="vital_readings")
    op.drop_table("vital_readings")
    op.drop_index("ix_medications_owner_id", table_name="medications")
    op.drop_table("medications")
    op.drop_index("ix_lab_reports_owner_collected", table_name="lab_reports")
    op.drop_table("lab_reports")
    op.drop_index("ix_health_shares_viewer_id", table_name="health_shares")
    op.drop_table("health_shares")
    op.drop_index("ix_activity_entries_owner_time", table_name="activity_entries")
    op.drop_table("activity_entries")
    # ### end Alembic commands ###
