"""add recipes, ingredients and steps

Revision ID: 8014dbc3500f
Revises: 31c70e123e67
Created: 2026-07-30 22:12:34.701091+00:00

Phase 5a of SPEC §4.6: recipes with structured ingredient rows, ordered steps,
tags and search.

Two things here are not autogenerate's work and matter:

* **`ingredients` is a shared, case-insensitively unique vocabulary.** The
  unique index is on `lower(name)`, which is what stops "Flour" and "flour"
  becoming two rows the shopping list can never combine.
* **The `access_permissions.module` CHECK**, widened again for `kitchen`. The
  same one-line edit each module has needed, which is exactly the reviewable
  line the "TEXT + CHECK, never Postgres ENUM" decision was taken for.

`recipe_ingredients.ingredient_id` is ON DELETE RESTRICT, not CASCADE: tidying
the ingredient vocabulary must never silently empty somebody's recipe.

Reversible: `downgrade()` drops the five tables and narrows the CHECK, deleting
any deviation naming a module that no longer exists. Uploaded image files are
NOT touched — they live on a volume, this migration cannot see them, and
deleting a user's photographs on a schema rollback would be indefensible. They
become orphans, which `scripts/` can report on.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8014dbc3500f"
down_revision: str | None = "31c70e123e67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("aisle", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_ingredients_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
    )
    op.create_index("ix_ingredients_aisle", "ingredients", ["aisle"], unique=False)
    op.create_index(
        "uq_ingredients_name", "ingredients", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("servings", sa.Integer(), server_default=sa.text("4"), nullable=False),
        sa.Column("prep_minutes", sa.Integer(), nullable=True),
        sa.Column("cook_minutes", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("image_key", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cook_minutes IS NULL OR cook_minutes >= 0",
            name=op.f("ck_recipes_cook_minutes_not_negative"),
        ),
        sa.CheckConstraint("length(trim(title)) > 0", name=op.f("ck_recipes_title_not_blank")),
        sa.CheckConstraint(
            "prep_minutes IS NULL OR prep_minutes >= 0",
            name=op.f("ck_recipes_prep_minutes_not_negative"),
        ),
        sa.CheckConstraint("servings > 0", name=op.f("ck_recipes_servings_positive")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_recipes_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    op.create_index("ix_recipes_owner_id", "recipes", ["owner_id"], unique=False)
    op.create_index(
        "ix_recipes_search_vector",
        "recipes",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_recipes_title", "recipes", ["title"], unique=False)
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity > 0", name=op.f("ck_recipe_ingredients_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_recipe_ingredients_ingredient_id_ingredients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_ingredients_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_ingredients")),
    )
    op.create_index(
        "ix_recipe_ingredients_ingredient_id", "recipe_ingredients", ["ingredient_id"], unique=False
    )
    op.create_index(
        "ix_recipe_ingredients_recipe_id",
        "recipe_ingredients",
        ["recipe_id", "position"],
        unique=False,
    )
    op.create_table(
        "recipe_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.CheckConstraint("length(trim(body)) > 0", name=op.f("ck_recipe_steps_body_not_blank")),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_steps_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_steps")),
    )
    op.create_index(
        "ix_recipe_steps_recipe_id", "recipe_steps", ["recipe_id", "position"], unique=False
    )
    op.create_table(
        "recipe_tags",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.CheckConstraint("length(trim(tag)) > 0", name=op.f("ck_recipe_tags_tag_not_blank")),
        sa.CheckConstraint("tag = lower(tag)", name=op.f("ck_recipe_tags_tag_is_lowercase")),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_tags_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("recipe_id", "tag", name=op.f("pk_recipe_tags")),
    )
    op.create_index("ix_recipe_tags_tag", "recipe_tags", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Deviations naming a module that is about to stop existing would violate
    # the narrower CHECK, so they go first.
    op.execute("DELETE FROM access_permissions WHERE module = 'kitchen'")
    op.drop_constraint("module_is_known", "access_permissions", type_="check")
    op.create_check_constraint(
        "module_is_known",
        "access_permissions",
        "module IN ('users', 'settings', 'audit', 'tasks', 'notes', 'calendar')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recipe_tags_tag", table_name="recipe_tags")
    op.drop_table("recipe_tags")
    op.drop_index("ix_recipe_steps_recipe_id", table_name="recipe_steps")
    op.drop_table("recipe_steps")
    op.drop_index("ix_recipe_ingredients_recipe_id", table_name="recipe_ingredients")
    op.drop_index("ix_recipe_ingredients_ingredient_id", table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_index("ix_recipes_title", table_name="recipes")
    op.drop_index("ix_recipes_search_vector", table_name="recipes", postgresql_using="gin")
    op.drop_index("ix_recipes_owner_id", table_name="recipes")
    op.drop_table("recipes")
    op.drop_index("uq_ingredients_name", table_name="ingredients")
    op.drop_index("ix_ingredients_aisle", table_name="ingredients")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
